author: boozaa
database: true
description: "Plugin BooCron - Implementation of Cron4J"
generator: Boozaa Bukkit Generator
main: org.shortrip.boozaa.plugins.boocron.BooCron
name: BooCron
startup: POSTWORLD
version: '0.2'
